### ISSUE TITLE
Feature Request - Add ability to pass in colors via URL

### ISSUE THREAD

**Issue by vmitchell85** [javisperez/tailwindcolorshades#1]
It'd be awesome to have some sort of URL params you can pass to set the colors.

Then you can save the url to always get back to it.

I'd be down to create a PR at some point for this but currently have a lot of projects.

Thanks for an awesome tool!

**Comment by javisperez** [comment]
Hey, thanks for the issue!

Yeah, shareable URL's are planned but haven't got the time to implement it yet.

Thanks for the support 👍
