### ISSUE TITLE
Change URL when renaming palettes

### ISSUE THREAD

**Issue by MarvinJWendt** [javisperez/tailwindcolorshades#15]
Hey, thank you for this awesome tool!
I noticed that the URL does not adjust to the renamed color names. When I copy the permalink and want to send it to a colleague, or save it, I have to manually change the names of the colors in the URL. It would be cool if this would happen automatically. Thanks in advance!

**Comment by javisperez** [comment]
Hey, thanks for the issue! 
Yeah i hadn't notice before lol but you are right and that's a bug, I'll fix it on this week, thanks for pointing that out!

**Comment by javisperez** [comment]
This is now in prod :) thanks again for the issue!
