### ISSUE TITLE
[Feature Request] Add new 950 shade to match TailwindCSS 3.3 

### ISSUE THREAD

**Issue by florianbouvot** [javisperez/tailwindcolorshades#36]
Hi @javisperez,

Can you add a new 950 shade to match TailwindCSS 3.3 release: https://tailwindcss.com/blog/tailwindcss-v3-3#extended-color-palette-for-darker-darks

Thank you, Florian.

**Comment by javisperez** [comment]
This is done now :), thanks for the issue.

**Comment by florianbouvot** [comment]
@javisperez thank you
