### ISSUE TITLE
Color picker would be cool

### ISSUE THREAD

**Issue by CanRau** [javisperez/tailwindcolorshades#9]
Thanks for this awesome tool 🙏 
What do you think about a color picker like [vue-color](https://github.com/xiaokaike/vue-color)?

**Comment by javisperez** [comment]
Hey! sorry for the late (very late) reply. I think this is a good idea, I'll try to take a look into it and add it somehow, thank you for the issue!

**Comment by msakrejda** [comment]
@javisperez just changing color selection to `<input type="color" />` can be used in [modern browsers](https://caniuse.com/#feat=input-color). Tried that via DOM inspector and it just works (though would need some styling changes). Came here to file an issue but found this one.

Thanks for the neat tool!

**Comment by ArsalaBangash** [comment]
@uhoh-itsmaciek Thank you for investigating. Would you be able to create a PR to help others out?

**Comment by MrSunshyne** [comment]
@javisperez @ArsalaBangash i've[ sent a PR](https://github.com/javisperez/tailwindcolorshades/pull/13) for the same.

**Comment by javisperez** [comment]
Closing this as it's been implemented for a while now :)
